#include <filesystem>
#include <format>
#include <netcdf>
#include <print>
#include <stdexcept>
#include <vector>
#include <chrono>
// Defining BOOST_DISABLE_ASSERTS disables range checking for
// variables of type boost::multi_array:
//#define BOOST_DISABLE_ASSERTS
#include <boost/multi_array.hpp>
#include <boost/math/interpolators/makima.hpp>
#include "roms_forcing_utils.h"

namespace fs = std::filesystem;
using boost::math::interpolators::makima;

// Structure representing a point on earth:
struct Point {
    double x, y;
};

// Check if a give point is within a given polygon
// Code generated by ChatGPT, see also:
// https://wrfranklin.org/Research/Short_Notes/pnpoly.html
bool pointInPolygon(const std::vector<Point>& poly, Point p) {
    bool inside = false;
    int n = poly.size();

    for (int i = 0, j = n - 1; i < n; j = i++) {
        const Point& a = poly[i];
        const Point& b = poly[j];

        bool intersect =
            ((a.y > p.y) != (b.y > p.y)) &&
            (p.x < (b.x - a.x) * (p.y - a.y) / (b.y - a.y) + a.x);

        if (intersect)
            inside = !inside;
    }
    return inside;
}

// Create river runoff Netcdf file and write data
void ROMS_forcing::save_river_freshwater(std::string out_file, std::string tfreq,
    boost::multi_array<float,3> data, std::string river_input_file, int days_per_yr)
{
    float cycle_length = (float)days_per_yr;
    std::vector<float> dates;
    if (tfreq.empty()) {
        throw "argument \"tfreq\" must not be empty";
    }
    if (tfreq == "monthly") {
        for (int d=15; d<=360; d+=30) dates.push_back(d*days_per_yr/360.0);
    } else if (tfreq == "daily") {
        for (float d=0.5; d<=days_per_yr; d+=1.0) dates.push_back(d);
    } else if (tfreq.back() == 'h') {
        // Remove last character from tfreq and (try to) convert the remaining string
        // to an integer:
        tfreq.erase(tfreq.length()-1);
        int time_freq_hours = std::stoi(tfreq);
        if (time_freq_hours <= 0) throw(std::format("invalid time frequency: {}h", tfreq));
        float dt = time_freq_hours/24.0;
        for (float d=dt/2; d<=days_per_yr; d+=dt) dates.push_back(d);
    } else {
        throw(std::format("invalid time frequency: {}", tfreq));
    }
    // Read dimension sizes from grid file:
    NcFile nc_grd;
    std::map<std::string,int> dim_size;
    std::multimap<std::string,NcDim> ncdims;
    nc_grd.open(ROMS_gridfile, NcFile::read);
    // Store sizes of all dimensions in map "dim_size":
    ncdims = nc_grd.getDims();
    for (auto it = ncdims.begin(); it != ncdims.end(); it++) {
        dim_size[it->second.getName()] = it->second.getSize();
    }
    size_t nx = dim_size["xi_rho"];
    size_t ny = dim_size["eta_rho"];
    // Create output file:
    NcFile nc_out(out_file, NcFile::FileMode::replace, NcFile::FileFormat::nc4);
    nc_out.addDim("swf_time", dates.size());
    nc_out.addDim("eta_rho", ny);
    nc_out.addDim("xi_rho", nx);
    // Create variable "swf_time":
    const char *attval = new char[128];
    char *attval_buf = new char[128];
    NcVar v_time  = nc_out.addVar("swf_time", "double", "swf_time");
    attval = "time";
    v_time.putAtt("long_name", NcType::nc_CHAR, strlen(attval), attval);
    v_time.putAtt("cycle_length", NcType::nc_INT, days_per_yr);
    sprintf(attval_buf, "%i_day", days_per_yr);
    v_time.putAtt("calendar", NcType::nc_CHAR, strlen(attval_buf), attval_buf);
    attval = "T";
    v_time.putAtt("axis", NcType::nc_CHAR, strlen(attval), attval);
    // Create variable "swflux":
    NcVar v_sw  = nc_out.addVar("swflux", "float", {"swf_time", "eta_rho", "xi_rho"});
    attval = "Freshwater flux from river runoff";
    v_sw.putAtt("long_name", NcType::nc_CHAR, strlen(attval), attval);
    attval = "cm day-1";
    v_sw.putAtt("units", NcType::nc_CHAR, strlen(attval), attval);
    attval = "Dai et al. (2009) climatological runoff data";
    v_sw.putAtt("description", NcType::nc_CHAR, strlen(attval), attval);
    attval = "lon_rho lat_rho";
    v_sw.putAtt("coordinates", NcType::nc_CHAR, strlen(attval), attval);
    // Global attributes:
    attval = "River freshwater runoff, regridded data";
    nc_out.putAtt("title", NcType::nc_CHAR, strlen(attval), attval);
    attval = "ROMS forcing file";
    nc_out.putAtt("type", NcType::nc_CHAR, strlen(attval), attval);
    sprintf(attval_buf, "Source: %s", river_input_file.c_str());
    nc_out.putAtt("remark1", NcType::nc_CHAR, strlen(attval_buf), attval_buf);
    sprintf(attval_buf, "ROMS grid file: %s", ROMS_gridfile.c_str());
    nc_out.putAtt("remark2", NcType::nc_CHAR, strlen(attval_buf), attval_buf);
    auto t_now = std::chrono::system_clock::now();
    std::time_t curTime = std::chrono::system_clock::to_time_t(t_now);
    auto tmp = std::string(std::ctime(&curTime));
    // Unfortunately, tmp may have a newline at the end, so we remove it:
    tmp.erase(tmp.find_last_not_of("\n") + 1);
    sprintf(attval_buf, "Created on: %s", tmp.c_str());
    nc_out.putAtt("date", NcType::nc_CHAR, strlen(attval_buf), attval_buf);
    // Write data:
    v_time.putVar(&dates[0]);
    v_sw.putVar(&data[0][0][0]);
    // Free pointer(s):
    delete[] attval_buf;
}

// Create river runoff file on the ROMS grid, spread over a specified number of
// ROMS grid cells. The data is created for a leap year.
// Based on make_river_freshwater.m from the ROMStools.
// Arguments:
//   - river_input_file: path to Netcdf file containing Dai et al. (2009) data
//   - outdir: folder where output Netcdf file is to be stored
//   - time_res: the resolution of the river forcing (in hours)
//   - spreading: how to spread river input among neighbouring grid cells ("gaussian", anything
//     else results in linearly decreasing spreading)
std::string ROMS_forcing::make_river_freshwater(std::string river_input_file, 
    std::string outdir, int time_res, std::string spreading)
{
    std::println("\n------- START of ROMS_forcing::make_river_freshwater -------");
    std::println("river_input_file = {}", river_input_file);
    // Check if output file exists: assume nothing needs to be done
    // if this is the case:
    std::string r_tag = ROMS_setup;
    // Convert r_tag to lowercase:
    transform(r_tag.begin(), r_tag.end(), r_tag.begin(), ::tolower);
    std::println("r_tag = {}", r_tag);
    std::string output_file = std::format("{}/{}_{}h_river_frc_366d.nc", output_dir, r_tag, time_res);
    std::println("output file = {}", output_file);
    const fs::path p_out_file{output_file};
    if (fs::exists(p_out_file)) {
        std::println("found river runoff on ROMS grid: {}", output_file);
        std::println("make_river_freshwater: nothing to be done, exiting");
        std::println("------- END of ROMS_forcing::make_river_freshwater -------\n");
        std::cout << std::flush;
        return output_file;
    }
    // Check if time_res is a valid time interval: it must divide 24
    if (24%time_res != 0) {
        throw std::runtime_error(std::format("invalid time resolution: {} (must be a divisor of 24)",
            time_res));
    }
    if (verbose) std::println("compute river runoff on ROMS grid");
    // Load observational data:
    std::map<std::string,int> dim_size, dim_size_grd;
    std::multimap<std::string,NcDim> ncdims, ncdims_grd;
    NcFile nc_Dai, nc_grd;
    NcVar v_Dai, v_grd;
    nc_Dai.open(river_input_file, NcFile::read);
    // Store sizes of all dimensions in map "dim_size":
    ncdims = nc_Dai.getDims();
    for (auto it = ncdims.begin(); it != ncdims.end(); ++it) {
        dim_size[it->second.getName()] = it->second.getSize();
    }
    size_t nriv = dim_size["station"];
    size_t nt_clim = dim_size["time_clim"];
    std::println("   total number of rivers = {}", nriv);
    std::cout << std::flush;
    float *Lon_dat = new float[nriv];
    float *Lat_dat = new float[nriv];
    // The shape of "flow" is: nt_clim, nriv
    float *flow = new float[nt_clim*nriv];
    v_Dai = nc_Dai.getVar("lon_mou");
    v_Dai.getVar(Lon_dat);
    v_Dai = nc_Dai.getVar("lat_mou");
    v_Dai.getVar(Lat_dat);
    v_Dai = nc_Dai.getVar("FLOW_CLIM");
    v_Dai.getVar(flow);  // shape nt_clim, nriv
    nc_Dai.close();
    // Make sure Lon_dat is in [0,360]:
    for (size_t i=0; i<nriv; ++i) {
        if (Lon_dat[i] < 0.0) Lon_dat[i] += 360.0;
    }
    // Convert Lon_dat and Lat_dat to radians:
    constexpr double deg2rad = std::numbers::pi/180.0;
    for (int i=0; i<nriv; ++i) {
        Lon_dat[i] *= deg2rad;
        Lat_dat[i] *= deg2rad;
    }
    // Load variables related to the ROMS grid:
    nc_grd.open(ROMS_gridfile, NcFile::read);
    // Store sizes of all dimensions in map "dim_size":
    ncdims_grd = nc_grd.getDims();
    for (auto it = ncdims_grd.begin(); it != ncdims_grd.end(); ++it) {
        dim_size_grd[it->second.getName()] = it->second.getSize();
    }
    size_t nx = dim_size_grd["xi_rho"];
    size_t ny = dim_size_grd["eta_rho"];
    size_t nxy = nx*ny;
    double *lon_rho = new double[nxy];
    double *lat_rho = new double[nxy];
    double *mask_rho = new double[nxy];
    double *pm = new double[nxy];
    double *pn = new double[nxy];
    double *area = new double[nxy];
    v_grd = nc_grd.getVar("lon_rho");  // shape ny, nx
    v_grd.getVar(lon_rho);
    v_grd = nc_grd.getVar("lat_rho");
    v_grd.getVar(lat_rho);
    v_grd = nc_grd.getVar("mask_rho");
    v_grd.getVar(mask_rho);
    v_grd = nc_grd.getVar("pm");
    v_grd.getVar(pm);
    v_grd = nc_grd.getVar("pn");
    v_grd.getVar(pn);
    nc_grd.close();
    for (int i=0; i<nxy; ++i) area[i] = 1/(pm[i]*pn[i]);
    // Make sure lon_rho is in [0,360]:
    for (size_t i=0; i<nxy; ++i) {
        if (lon_rho[i] < 0.0) lon_rho[i] += 360.0;
    }
    // Convert lon_rho and lat_rho to radians:
    for (int i=0; i<nxy; ++i) {
        lon_rho[i] *= deg2rad;
        lat_rho[i] *= deg2rad;
    }

    // Construct polygon representing the boundary of the
    // ROMS domain:
    std::vector<Point> plist;
    // Maximum latitude (only needed for SO setups):
    double lat_max = -90.0;
    for (int i=0; i<nx; ++i) {
        // indices 0, i: "south" of ROMS domain
        plist.push_back(Point(lon_rho[i],lat_rho[i]));
        if (lat_rho[i]>lat_max) lat_max = lat_rho[i];
    }
    for (int j=1; j<ny; ++j) {
        // indices j, nx-1: "east" of ROMS domain
        plist.push_back(Point(lon_rho[j*nx+nx-1],lat_rho[j*nx+nx-1]));
        if (lat_rho[j*nx+nx-1]>lat_max) lat_max = lat_rho[j*nx+nx-1];
    }
    for (int i=nx-2; i>=0; --i) {
        // indices ny-1, i: "north" of ROMS domain
        plist.push_back(Point(lon_rho[(ny-1)*nx+i],lat_rho[(ny-1)*nx+i]));
        if (lat_rho[(ny-1)*nx+i]>lat_max) lat_max = lat_rho[(ny-1)*nx+i];
    }
    for (int j=ny-2; j>=0; --j) {
        // indices j, 0: "west" of ROMS domain
        plist.push_back(Point(lon_rho[j*nx],lat_rho[j*nx]));
        if (lat_rho[j*nx]>lat_max) lat_max = lat_rho[j*nx];
    }
    if (verbose) std::println("   figure out which rivers are in the ROMS domain");
    std::vector<int> river_in;
    bool riv_in;
    // Find rivers in ROMS domain and adjust some rivers manually:
    if (r_tag == "pactcs30" || r_tag == "humpac15") {
        // Loop over the rivers and check if their mouth is within the ROMS
        // domain. Additionally, some rivers are turned on or off manually.
        for (int r=0; r<nriv; ++r) {
            if (pointInPolygon(plist, Point(Lon_dat[r],Lat_dat[r]))) {
                riv_in = true;
                // Manually exclude some rivers:
                if (Lat_dat[r]>65.0) {
                    // North Pacific:
                    riv_in = false;
                } else if (Lon_dat[r]>300.0) {
                    riv_in = false;
                } else if (Lon_dat[r]>260.0 && Lon_dat[r]<270.0 &&
                           Lat_dat[r]>17.0 && Lat_dat[r]<23.0) {
                    // Central America
                    riv_in = false;
                } else if (Lon_dat[r]>280.0 && Lon_dat[r]<282.0 && 
                           Lat_dat[r]>9.0 && Lat_dat[r]<11.0) {
                    // Central America
                    riv_in = false;
                }
            } else {
                riv_in = false;
                // Manually include some rivers:
                if (Lon_dat[r]>236.0 && Lon_dat[r]<240.0 && Lat_dat[r]>37.0 && Lat_dat[r]<42.0) {
                    // NW Pacific:
                    riv_in = true;
                }
            }
            // Add current river to list of included rivers:
            if (riv_in) river_in.push_back(r);
        }
    } else if (r_tag == "pacsg") {
        // Loop over the rivers and check if their mouth is within the ROMS
        // domain. Additionally, manually correct some rivers.
        for (int r=0; r<nriv; ++r) {
            if (pointInPolygon(plist, Point(Lon_dat[r],Lat_dat[r]))) {
                riv_in = true;
                // Manually exclude some rivers:
                if (Lon_dat[r]>260 && Lon_dat[r]<270 && Lat_dat[r]>17 && Lat_dat[r]<30) {
                    // Mexican Gulf
                    riv_in = false;
                } else if (Lon_dat[r]>273 && Lon_dat[r]<276 && Lat_dat[r]>13 && Lat_dat[r]<14) {
                    // Central America
                    riv_in = false;
                } else if (Lon_dat[r]>300 && Lon_dat[r]<310 && Lat_dat[r]>-32 && Lat_dat[r]<-28) {
                    // Central America
                    riv_in = false;
                }
            } else {
                riv_in = false;
                // Manually include some rivers:
                if (Lon_dat[r]>220 && Lon_dat[r]<240 && Lat_dat[r]>30 && Lat_dat[r]<60) {
                    // NW Pacific
                    riv_in = true;
                }
            }
            if (riv_in) river_in.push_back(r);
        }
    } else if (r_tag == "so_d05" || r_tag == "so_d025" || r_tag == "so_d0125") {
        if (verbose) std::println("   maximum ROMS rho latitude = {}", lat_max);
        for (int r=0; r<nriv; r++) {
            // Include rivers whose latitude is at most lat_max:
            if (Lat_dat[r] <= lat_max) river_in.push_back(r);
        }
    } else {
        throw std::runtime_error(std::format("make_river_freshwater: ROMS setup '{}' not implemented!", r_tag));
    }
    if (verbose) std::println("   number of rivers in ROMS domain = {}", river_in.size());

    // Initialize river load field on ROMS grid, with the same time resulution as
    // the river input data:
    typedef boost::multi_array<float, 3> array_3d;
    typedef array_3d::index index;
    array_3d flow_clim(boost::extents[nt_clim][ny][nx]);
    // Initialize flow_clim to 0:
    std::fill(flow_clim.data(), flow_clim.data()+flow_clim.num_elements(), 0.0);
    // Go through rivers lying within the ROMDS domain and find closest grid point:
    if (verbose) std::println("   find grid cells nearest to river mouths on ROMS grid");
    std::cout << std::flush;
    float score, score_min;
    int i_min, j_min;
    for (auto r : river_in) {
        i_min = -1;
        j_min = -1;
        score_min = 1e23;
        for (int j=0; j<ny; ++j) {
            for (int i=0; i<nx; ++i) {
                if (mask_rho[j*nx+i] == 1) {
                    // Ocean:
                    score = (Lon_dat[r]-lon_rho[j*nx+i])*(Lon_dat[r]-lon_rho[j*nx+i]) +
                            (Lat_dat[r]-lat_rho[j*nx+i])*(Lat_dat[r]-lat_rho[j*nx+i]);
                    if (score < score_min) {
                        // Store new minimum along with its index:
                        score_min = score;
                        i_min = i;
                        j_min = j;
                    }
                }
            }
        }
        // Add freshwater flux to each time record:
        for (index m=0; m<nt_clim; ++m) {
            // Reminder: flow has shape nt_clim, nriv
            // Thus flow(r,m) in Matlab is flow[m*nriv+r] here.
            if (!std::isnan(flow[m*nriv+r])) {
                if (r == 16 && r_tag=="pactcs30") {
                    // Make sure Amur is added in Sea of Okhotsk
                    //FLOW(88,105,m) = FLOW(88,105,m) + flow(r,m);
                    flow_clim[m][104][87] = flow_clim[m][104][87] + flow[m*nriv+r];
                } else {
                    //FLOW(i,j,m) = FLOW(i,j,m) + flow(r,m);
                    flow_clim[m][j_min][i_min] = flow_clim[m][j_min][i_min] + flow[m*nriv+r];
                }
            }
        }
    }

    // Spread river outflow on the surface:
    int extraboxes, istart, iend, jstart, jend, idx;
    float *dist, *dist_weighted;
    // Minimum 
    int min_extraboxes = 9;
    std::println("   spreading river discharge on area, weighted by distance squared");
    std::cout << std::flush;
    array_3d flow_spread(boost::extents[nt_clim][ny][nx]);
    int count = 0;
    int countextrab = 0;
    float NaNf = nanf("mynan");
    double dlon, dlat, dist_total;
    float dist_max = -1e8;
    float dist_new;
    // Mean earth radius IUGG:
    double er = 6371.009;
    // Inititalize flow_spread:
    std::fill(flow_spread.data(), flow_spread.data()+flow_spread.num_elements(), 0.0);
    // Loop for spreading flow_clim:
    for (index m=0; m<nt_clim; ++m) {
        for (index j=0; j<ny; ++j) {
            for (index i=0; i<nx; ++i) {
                if (flow_clim[m][j][i] > 0.0) {
                    // Number of surrounding indices to take: min=3, max=7 depending on
                    // absolute water runoff  
                    // (the max option was for the case of the "constant radius" spread)
                    extraboxes = std::trunc(std::log10(flow_clim[m][j][i])) + min_extraboxes;
                    if (std::trunc(std::log10(flow_clim[m][j][i]))<0) {
                        // Give a warning if the number of boxes was reduced (so users can
                        // make sure that they have a decent number of extraboxes:
                        std::println("   ** warning: log10(flow_clim)<0 ** --> "
                            "log10(flow_clim) = {} --> extraboxes = {}",
                            std::trunc(std::log10(flow_clim[m][j][i])), extraboxes);
                        std::cout.flush();
                    }
                    // Define box indices, on ROMS grid:
                    istart = std::max(0,((int)i-extraboxes));
                    jstart = std::max(0,((int)j-extraboxes));
                    iend = std::min((int)nx-1,((int)i+extraboxes));
                    jend = std::min((int)ny-1,((int)j+extraboxes));
                    // Allocate arrays of shape jend-jstart+1, iend-istart+1:
                    dist = new float[(iend-istart+1)*(jend-jstart+1)];
                    dist_weighted = new float[(iend-istart+1)*(jend-jstart+1)];
                    for (int k=0; k<(iend-istart+1)*(jend-jstart+1); ++k) dist[k] = NaNf;
                    // Compute distances from cell (j,i):
                    dist_max = -1e8;
                    for (int jbox=jstart; jbox<=jend; ++jbox)
                        for (int ibox=istart; ibox<=iend; ++ibox)
                            if (mask_rho[jbox*nx+ibox]==1) {
                                dlat = lat_rho[jbox*nx+ibox] - lat_rho[j*nx+i];
                                dlon = lon_rho[jbox*nx+ibox] - lon_rho[j*nx+i];
                                dist_new = er*2*std::asin(
                                    std::sqrt(
                                        std::sin(0.5*dlat)*std::sin(0.5*dlat) +
                                        std::cos(lat_rho[jbox*nx+ibox])*std::cos(lat_rho[j*nx+i]) *
                                        std::sin(0.5*dlon)*std::sin(0.5*dlon)
                                    ));
                                dist[(jbox-jstart)*(iend-istart+1)+ibox-istart] = dist_new;
                                if (dist_new > dist_max) dist_max = dist_new;
                            }
                    // Construct weighting array:
                    if (spreading == "gaussian") {
                        for (int jbox=jstart; jbox<=jend; ++jbox)
                            for (int ibox=istart; ibox<=iend; ++ibox) {
                                idx = (jbox-jstart)*(iend-istart+1)+ibox-istart;
                                // Weighting with the square of the distance:
                                dist_weighted[idx] = std::exp(-(dist[idx]/(dist_max/2))*(dist[idx]/(dist_max/2)));
                            }
                        }
                    else {
                        for (int jbox=jstart; jbox<=jend; ++jbox)
                            for (int ibox=istart; ibox<=iend; ++ibox) {
                                idx = (jbox-jstart)*(iend-istart+1)+ibox-istart;
                                dist_weighted[idx] = 1-(dist[idx]/dist_max);
                            }
                    }
                    // Normalize dist_weighted so that it contains weights:
                    dist_total = 0.0;
                    for (int jbox=jstart; jbox<=jend; ++jbox)
                        for (int ibox=istart; ibox<=iend; ++ibox) {
                            idx = (jbox-jstart)*(iend-istart+1)+ibox-istart;
                            if (!std::isnan(dist_weighted[idx])) dist_total += dist_weighted[idx];
                        }
                    for (int jbox=jstart; jbox<=jend; ++jbox)
                        for (int ibox=istart; ibox<=iend; ++ibox) {
                            idx = (jbox-jstart)*(iend-istart+1)+ibox-istart;
                            dist_weighted[idx] = dist_weighted[idx]/dist_total;
                        }
                    // Spread the weighted data across the box:
                    for (int jbox=jstart; jbox<=jend; ++jbox)
                        for (int ibox=istart; ibox<=iend; ++ibox)
                            if (mask_rho[jbox*nx+ibox]==1) {
                                idx = (jbox-jstart)*(iend-istart+1)+ibox-istart;
                                flow_spread[m][jbox][ibox] += flow_clim[m][j][i]*dist_weighted[idx];
                            }
                    delete[] dist, dist_weighted;
                }
            }
        }
    }

    // Change sign of river freshwater input and convert units: m3/s to cm/day
    for (index m=0; m<nt_clim; ++m)
        for (index j=0; j<ny; ++j)
            for (index i=0; i<nx; ++i)
                flow_spread[m][j][i] = -flow_spread[m][j][i]/area[j*nx+i]*86400*100;
    // Save monthly data to Netcdf file:
    std::string out_file_monthly = std::format("{}/{}_monthly_river_frc_366d.nc", output_dir, r_tag);
    std::println("save monthly data to file: {}", out_file_monthly);
    // We create the data for a leap year:
    int days_per_year = 366;
    save_river_freshwater(out_file_monthly, "monthly", flow_spread, river_input_file, days_per_year);

    // Interpolate monthly data to desired time resolution:
    std::println("interpolate from monthly to {}h fields", time_res);
    std::cout << std::flush;
    int nt_out = days_per_year*24/time_res;
    array_3d flow_spread_target(boost::extents[nt_out][ny][nx]);
    std::vector<float> dates_mon, dates_target;
    // Set up dates_mon such that if covers the whole period from 0 to 365/366 days:
    dates_mon.push_back(0.0);
    for (int d=15; d<=360; d+=30) dates_mon.push_back(d*days_per_year/360.0);
    dates_mon.push_back((float) days_per_year);
    // Backup copy of dates (needed later since dazes_mon will be emptied):
    std::vector<float> dates_mon_bak = dates_mon;
    float time_res_days = time_res / 24.0;
    for (float d=time_res_days/2; d<=days_per_year; d+=time_res_days) dates_target.push_back(d);
    std::vector<float> tmp_val, tmp;
    makima<std::vector<float>> interp({1.0f,2.0f,3.0f,4.0f}, {1.0f,2.0f,3.0f,4.0f});
    nt_out = dates_target.size();
    for (int j=0; j<ny; ++j)
        for (int i=0; i<nx; ++i) {
            tmp_val.clear();
            // Extend flow_spread[j][i] such that it corresponds to dates_mon:
            tmp_val.push_back(0.5*(flow_spread[0][j][i]+flow_spread[11][j][i]));
            for (int t=0; t<12; ++t) tmp_val.push_back(flow_spread[t][j][i]);
            tmp_val.push_back(0.5*(flow_spread[0][j][i]+flow_spread[11][j][i]));
            // std::println(".  tmp_val.size = {}", tmp_val.size());
            // std::println(".  dates.size = {}", dates_mon.size());
            interp = makima(std::move(dates_mon), std::move(tmp_val));
            for (int t=0; t<nt_out; ++t) {
                flow_spread_target[t][j][i] = interp(dates_target[t]);
            }
            // Fill dates_mon with previous content (it was moved and is thus empty right now):
            std::copy(dates_mon_bak.begin(), dates_mon_bak.end(), std::back_inserter(dates_mon));
        }
    // Write out data at desired time resolution:
    std::println("save data to file: {}", output_file);
    if (time_res == 24) {
        save_river_freshwater(output_file, "daily", flow_spread_target, river_input_file, days_per_year);
    } else {
        auto tfreq = std::format("{}h", time_res);
        save_river_freshwater(output_file, tfreq, flow_spread_target, river_input_file, days_per_year);
    }

    // Free pointers:
    delete[] Lat_dat, Lon_dat;
    delete[] flow, lon_rho, lat_rho, mask_rho, pm, pn, area;

    std::println("------- END of ROMS_forcing::make_river_freshwater -------\n");
    std::cout.flush();

    return output_file;
}